//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("DotNetDesign.Substrate")]
[assembly: AssemblyDescription("Library that provides smart entity structure for versioning and persisting.")]
[assembly: AssemblyCompany("DotNetDesign")]
[assembly: AssemblyProduct("DotNetDesign.Substrate")]
[assembly: AssemblyCopyright("Copyright (c) DotNetDesign 2011")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("8ba2a63c-ec50-4d4f-8290-3166d5931e8b")]
[assembly: AssemblyFileVersion("1.0.0.0")]


